# Generated by Django 6.0 on 2026-02-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_therapistprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='plan',
            field=models.CharField(default='Standard Plan', max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.therapistprofile'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
