# Generated by Django 6.0 on 2026-02-24 17:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_plan_patientprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='focus_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="e.g. ['Anxiety', 'Depression', 'Stress & burnout']"),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female therapist', 'Female therapist'), ('Male therapist', 'Male therapist'), ('Non-binary', 'Non-binary')], max_length=50, null=True),
        ),
    ]
