# Generated by Django 6.0 on 2026-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_address_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
