# Generated by Django 6.0 on 2026-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patientprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
