# Generated by Django 6.0 on 2026-01-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subjective_analysis', models.TextField(help_text='Patient reports, mood, etc.')),
                ('treatment_plan', models.TextField(help_text='Interventions & homework')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.patientprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.therapistprofile')),
            ],
        ),
    ]
