# Generated by Django 6.0 on 2026-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_clinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if note is still in progress'),
        ),
    ]
