# Generated by Django 6.0 on 2026-02-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_clinicalnote_is_draft'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.therapistprofile')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'unique_together': {('therapist', 'date', 'start_time')},
            },
        ),
    ]
