# Generated by Django 6.0 on 2026-02-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='observations',
            field=models.TextField(blank=True, help_text='Therapist objective observations', null=True),
        ),
    ]
