# Generated by Django 6.0 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_clinicalnote_appointment_clinicalnote_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this service from booking'),
        ),
    ]
