# Generated by Django 6.0 on 2026-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Clinic (Bangkok)', max_length=150)),
                ('address', models.TextField(blank=True, help_text='Full street address', null=True)),
                ('rooms', models.PositiveIntegerField(default=1, help_text='Number of available consultation rooms')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if location is closed for maintenance')),
            ],
        ),
    ]
